repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0  # Use the latest tag
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-ast
  - id: check-docstring-first
  - id: double-quote-string-fixer
  - id: debug-statements

- repo: https://github.com/psf/black
  rev: 22.3.0  # Use the latest tag
  hooks:
  - id: black
